---
# Docker installation tasks

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker-ce

- name: Clean APT cache
  ansible.builtin.apt:
    autoclean: yes
    autoremove: yes

- name: Install Docker
  ansible.builtin.apt:
    name: docker-ce
    state: present
  notify:
    - restart docker

# - name: Verify Docker repository
#   ansible.builtin.shell: apt-cache policy docker-ce
#   register: docker_repo_check

- name: Add existing user to Docker group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true

- name: Install Docker-Compose
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/v2.29.7/docker-compose-linux-x86_64"
    dest: "/usr/local/bin/docker-compose"
    mode: 0755
  notify: restart docker
