---
- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Allow SSH connections
  ufw:
    rule: allow
    name: OpenSSH

- name: Allow HTTP and HTTPS connections
  ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - "80"
    - "443"

- name: Enable UFW
  ufw:
    state: enabled
