# Ubuntu's Mainline Kernel
---
- name: Adding Ubuntu Mainline Kernel Repository
  become: true
  ansible.builtin.apt_repository:
    repo: "ppa:cappelikan/ppa"
    state: present

- name: Installing Ubuntu Mainline Kernel Tool (mainline)
  become: true
  ansible.builtin.apt:
    name: mainline
    state: present

- name: Install additional packages
  become: true
  ansible.builtin.apt:
    name:
      - libgee-0.8-dev
      - libjson-glib-dev
      - libvte-2.91-dev
      - valac
      - aria2
      - lsb-release
      - aptitude
    state: present

- name: Update all package repositories
  become: true
  ansible.builtin.apt:
    update_cache: yes
