# Main tasks
---
- name: Ensure system is Ubuntu
  assert:
    that:
      - ansible_distribution == "Ubuntu"
  when: ansible_os_family == "Debian"

- name: Include Ubuntu-specific tasks
  include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Installing Linux Apps
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    install_recommends: true
    state: present
  loop: "{{ common_packages  }}"

- include_tasks: nodejs.yml
- include_tasks: zsh.yml
- include_tasks: awscli.yml
- include_tasks: ruby.yml
- include_tasks: homebrew.yml
- include_tasks: flatpak.yml
- include_tasks: snap.yml
- include_tasks: teamviewer.yml
- include_tasks: chrome.yml
- include_tasks: docker.yml
- include_tasks: kubectl.yml
