---
- name: Copy generate_report.sh to the target machine
  ansible.builtin.copy:
    src: files/generate_report.sh
    dest: /usr/local/bin/generate_report.sh
    mode: "0755"

- name: Generate report
  ansible.builtin.command: /usr/local/bin/generate_report.sh

- name: Fetch the generated report
  ansible.builtin.fetch:
    src: /var/log/ansible_report.txt
    dest: ./reports/ansible_report.txt
    flat: yes
