---
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install common packages
  become: true
  apt:
    name: "{{ common_packages }}"
    state: present
    install_recommends: yes
