# Update all packages
---
- name: Upgrade all packages to the latest version
  become: true
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_only: true

- name: Remove dependencies that are no longer required
  become: true
  ansible.builtin.apt:
    autoremove: true

- name: Remove useless packages from the cache
  become: true
  ansible.builtin.apt:
    autoclean: true
