# Vault Installation
---
- name: Ensure unzip is installed
  become: true
  ansible.builtin.apt:
    name: unzip
    state: present

- name: Download Vault 1.18.0 .zip file
  become: true
  ansible.builtin.get_url:
    url: "https://releases.hashicorp.com/vault/1.18.0/vault_1.18.0_linux_amd64.zip"
    dest: "/tmp/vault_1.18.0_linux_amd64.zip"

- name: Unzip Vault binary
  become: true
  ansible.builtin.unarchive:
    src: "/tmp/vault_1.18.0_linux_amd64.zip"
    dest: /usr/local/bin
    remote_src: true
    mode: "0755"

- name: Verify Vault installation
  ansible.builtin.command: vault --version
  register: vault_version_check

- name: Display Vault version
  debug:
    var: vault_version_check.stdout
