---
# Default user obtained from the environment
ansible_user_id: "{{ lookup('env', 'USER') }}"

# NodeJS version
nodejs_version: "lts"

# Terraform versions to install
terraform_versions:
  - "0.12.31"
  - "0.13.7"
  - "0.14.11"
  - "0.15.5"
  - "1.0.4"

# AWS CLI version
awscli_version: "latest"

# Vault installation version
vault_version: "1.18.0"
