# Metadados
---
galaxy_info:
  author: calendario2009
  namespace: calendario2009
  role_name: ansible_playbook
  description: Setup Ubuntu Workstation with necessary tools and applications
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal

dependencies: []
