---
- name: Ensure required packages are installed (Debian/Ubuntu)
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - desktop-file-utils
    - libavahi-compat-libdnssd-dev
    - libx11-dev
    - libxtst-dev
    - libxinerama-dev
    - libxrandr-dev
    - libice-dev
    - libsm-dev
    - libssl-dev
  tags:
    - packages

- name: Download and install CMake {{ cmake_version }}
  ansible.builtin.get_url:
    url: "https://github.com/Kitware/CMake/releases/download/v{{ cmake_version }}/cmake-{{ cmake_version }}-linux-x86_64.sh"
    dest: "/tmp/cmake-{{ cmake_version }}-linux-x86_64.sh"
    mode: "0755"
  tags:
    - cmake

- name: Install CMake {{ cmake_version }}
  ansible.builtin.command:
    cmd: "/tmp/cmake-{{ cmake_version }}-linux-x86_64.sh --skip-license --prefix=/usr/local"
  tags:
    - cmake
