---
- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker-ce
    update_cache: true

- name: Clean APT cache
  ansible.builtin.apt:
    autoclean: yes
    autoremove: yes

- name: Install Docker
  ansible.builtin.apt:
    name: docker-ce
    state: present
  notify:
    - Restart Docker

- name: Add existing user to Docker group using gpasswd
  ansible.builtin.command:
    cmd: "sudo gpasswd -a {{ ansible_user_id }} docker"
  become: true

- name: Install Docker-Compose
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-x86_64"
    dest: "/usr/local/bin/docker-compose"
    mode: 0755
  notify: Restart Docker
