# Flatpak
---
- name: Flatpak install
  block:
    - name: Ensure Flatpak is installed and up-to-date
      become: true
      ansible.builtin.apt:
        name: flatpak
        state: latest
        update_cache: true

    - name: Ensure Flatpak remote is configured
      become: true
      ansible.builtin.command:
        cmd: "flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo"

    - name: Ensure Flathub is present
      become: true
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: system

    - name: Flatpak install packages
      become: true
      community.general.flatpak:
        name:
          - md.obsidian.Obsidian
          - com.microsoft.Edge
        state: present
