---
- name: Ensure required packages are installed (Debian/Ubuntu)
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - desktop-file-utils
    - libavahi-compat-libdnssd-dev
    - libx11-dev
    - libxtst-dev
    - libxinerama-dev
    - libxrandr-dev
    - libice-dev
    - libsm-dev
    - libssl-dev
  tags:
    - packages

- name: Add Kitware's GPG key (to fix GPG error)
  ansible.builtin.apt_key:
    url: https://apt.kitware.com/keys/kitware-archive-latest.asc
    state: present
  tags:
    - cmake

- name: Add Kitware APT repository for CMake
  ansible.builtin.apt_repository:
    repo: "deb https://apt.kitware.com/ubuntu/ {{ ansible_distribution_release }} main"
    state: present
    filename: kitware
  tags:
    - cmake

- name: Install CMake 3.21+
  ansible.builtin.apt:
    name: cmake
    state: latest
    update_cache: true
  tags:
    - cmake

- name: Add Qt6 PPA repository
  ansible.builtin.apt_repository:
    repo: "ppa:okirby/qt6-backports"
    state: present
  tags:
    - qt6

- name: Ensure Qt6 packages are installed
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - qt6-base-dev
    - qt6-tools-dev
    - qt6-tools-dev-tools
    - qt6-l10n-tools
  tags:
    - qt6

- name: Ensure OpenGL dependencies are installed
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - mesa-common-dev
  tags:
    - opengl

- name: Clone Input Leap repository
  ansible.builtin.git:
    repo: https://github.com/input-leap/input-leap.git
    dest: /opt/input-leap
    version: HEAD
    recursive: yes # Ensures submodules are cloned
  tags:
    - input-leap

- name: Create build directory
  ansible.builtin.file:
    path: /opt/input-leap/build
    state: directory
  tags:
    - build

- name: Run CMake configuration
  ansible.builtin.command:
    cmd: cmake -S. -Bbuild
    chdir: /opt/input-leap
  tags:
    - build

- name: Compile Input Leap
  ansible.builtin.command:
    cmd: cmake --build build
    chdir: /opt/input-leap
  tags:
    - build

- name: Install Input Leap
  ansible.builtin.command:
    cmd: cmake --install build
    chdir: /opt/input-leap
  tags:
    - install

- name: Ensure SSL directory exists
  ansible.builtin.file:
    path: /root/.local/share/InputLeap/SSL
    state: directory
    mode: "0755"
  tags:
    - ssl

- name: Ensure Fingerprints directory exists
  ansible.builtin.file:
    path: /root/.local/share/InputLeap/SSL/Fingerprints
    state: directory
    mode: "0755"
  tags:
    - ssl

- name: Generate a temporary SSL certificate if it doesn't exist
  ansible.builtin.shell: |
    openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 \
    -keyout /root/.local/share/InputLeap/SSL/InputLeap.key \
    -out /root/.local/share/InputLeap/SSL/InputLeap.pem \
    -subj "/CN=InputLeap"
  args:
    creates: /root/.local/share/InputLeap/SSL/InputLeap.pem
  tags:
    - ssl

- name: Run SSL fingerprint generation script
  ansible.builtin.command:
    cmd: /usr/local/bin/generate_fingerprint.sh
  tags:
    - ssl
