# Main tasks
---
- name: Ensure system is Ubuntu
  assert:
    that:
      - ansible_distribution == "Ubuntu"
  when: ansible_os_family == "Debian"

- name: Include Ubuntu-specific tasks
  include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Installing Linux Apps
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    install_recommends: true
    state: present
  loop: "{{ common_packages  }}"

- include_tasks: prechecks.yml
- include_tasks: rsyslog.yml
- include_tasks: reporting.yml
- include_tasks: zsh.yml
- include_tasks: nodejs.yml
- include_tasks: awscli.yml
- include_tasks: openSSL.yml
- include_tasks: java.yml
- include_tasks: latex.yml
- include_tasks: ruby.yml
- include_tasks: input-leap.yml
- include_tasks: homebrew.yml
- include_tasks: flatpak.yml
- include_tasks: snap.yml
- include_tasks: teamviewer.yml
- include_tasks: chrome.yml
- include_tasks: qBittorrent.yml
- include_tasks: flutter.yml
- include_tasks: docker.yml
- include_tasks: dbeaver.yml
- include_tasks: p4merge.yml
- include_tasks: kubectl.yml
- include_tasks: firewall.yml
- include_tasks: golang.yml
- include_tasks: gomplate.yml
- include_tasks: corectrl.yml
- include_tasks: vagrant.yml
- include_tasks: vault.yml
- include_tasks: openvpn.yml
- include_tasks: terraform.yml
- include_tasks: mainline_kernel.yml
- include_tasks: microsoft_edge.yml
- include_tasks: balena_etcher.yml
# - include_tasks: upgrade_all.yml
# - include_tasks: create_snapshot.yml
