---
- name: Ensure OpenVPN is installed
  ansible.builtin.apt:
    name: openvpn
    state: present
    update_cache: yes

- name: Verify if the OpenVPN configuration directory exists
  ansible.builtin.file:
    path: /etc/openvpn
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy OpenVPN server configuration from template
  ansible.builtin.template:
    src: server.conf.j2
    dest: /etc/openvpn/server.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart Openvpn

- name: Start and enable OpenVPN service using systemctl
  ansible.builtin.service:
    name: openvpn@server
    state: started
    enabled: true
  when: ansible_virtualization_type != "docker"
