---
- name: Ensure required packages are installed for Qt6
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - mesa-common-dev
  tags:
    - qt6

- name: Download and install Qt6 {{ qt6_version }}
  ansible.builtin.get_url:
    url: "https://download.qt.io/official_releases/qt/{{ qt6_version | regex_replace('^([0-9]+\\.[0-9]+).*$', '6.7') }}/{{ qt6_subversion }}/single/qt-everywhere-src-{{ qt6_subversion }}.tar.xz"
    dest: "/tmp/qt-everywhere-src-{{ qt6_subversion }}.tar.xz"
    mode: "0755"
  tags:
    - qt6

- name: Extract Qt6 archive
  ansible.builtin.unarchive:
    src: "/tmp/qt-everywhere-src-{{ qt6_subversion }}.tar.xz"
    dest: "/opt"
    remote_src: yes
  tags:
    - qt6

- name: Create build directory for Qt6
  ansible.builtin.file:
    path: "/opt/qt-everywhere-src-{{ qt6_subversion }}/build"
    state: directory
  tags:
    - qt6

- name: Run configure for Qt6
  ansible.builtin.command:
    cmd: "./configure"
    chdir: "/opt/qt-everywhere-src-{{ qt6_subversion }}/qtbase"
  tags:
    - qt6

- name: Compile Qt6
  ansible.builtin.command:
    cmd: "make"
    chdir: "/opt/qt-everywhere-src-{{ qt6_subversion }}/qtbase"
  tags:
    - qt6

- name: Install Qt6
  ansible.builtin.command:
    cmd: "make install"
    chdir: "/opt/qt-everywhere-src-{{ qt6_subversion }}/qtbase"
  tags:
    - qt6
