---
- name: Install rsyslog
  ansible.builtin.apt:
    name: rsyslog
    state: present

- name: Configure rsyslog
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
  notify:
    - Restart Rsyslog
