---
- name: Install Ruby dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    install_recommends: yes
  loop:
    - autoconf
    - bison
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm6
    - libgdbm-dev
    - libdb-dev
    - curl
    - g++
    - gcc
    - automake
    - libc6-dev
    - libtool
    - sqlite3
    - pkg-config
  tags:
    - ruby-deps

# Instalação do Rbenv e Ruby via Rbenv
- name: Install Rbenv
  ansible.builtin.git:
    repo: "{{ rbenv_repo }}"
    dest: "{{ rbenv_path }}"
  tags:
    - rbenv

- name: Install ruby-build plugin for Rbenv
  ansible.builtin.git:
    repo: "{{ ruby_build_repo }}"
    dest: "{{ rbenv_path }}/plugins/ruby-build"
  tags:
    - rbenv

- name: Add Rbenv to the Zsh environment
  ansible.builtin.lineinfile:
    path: "{{ zshrc_path }}"
    regexp: 'export PATH="\$HOME/.rbenv/bin:\$PATH"'
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
    state: present
  tags:
    - rbenv

- name: Initialize Rbenv in the Zsh shell
  ansible.builtin.lineinfile:
    path: "{{ zshrc_path }}"
    regexp: 'eval "\$\(rbenv init -\)"'
    line: 'eval "$(rbenv init -)"'
    state: present
  tags:
    - rbenv
